= Draft Release notes for version 0.1.14 (release date: xx.08.2021)

.Added banks
|===
|===

== Notices:
- `Xs2aHttpLogSanitizer` was extended with new headers to hide.
- added Decoupled, and Embedded Pre-step flows to the XS2A Flows documentation. Amended mistakes in the Adapter arc42 page.
- refactored `santander-adapter`: added validations, marked some API endpoints as unsupported based on the bank documentation.
- renamed 'PreAuthorisationException' into more generic `RequestAuthorizationValidationException`.
- `AccessTokenService` and `AccessTokenException` are moved to `xs2a-adapter-service-api` package.
- added `Glossary` to the Adapter arc42 document.
- completed `Building Block View` chapter of the Adapter arc42 document.

== Features:
- `deutsche-bank-adapter` removes subaccount number from PSU-ID for DE/DB and DE/Noris if present.

== Fixes:
- fixed `unicredit-adapter` update payment psu data failing because of invalid links format in response.
- fixed `santander-adapter` OAuth2Service.
- fixed swallowing original bank error when throwing `AccessTokenException` in `CrealogixEmbeddedPreAuthorisationService`.
- fixed Postman collection for `unicredit-adapter`
