= DRAFT Release notes for version 0.1.2 (release date: xx.09.2020)

.Added banks
|===
|
|===

== Notices:
- Documentation was published on GitHub Pages and available by referencing to https://adorsys.github.io/xs2a-adapter/
- Migration from PFB business entity to DB in deutsche bank adapter.
Requires urls in the aspsp-registry to be changed.
In this release both business entities are supported.
In the next release PFB support will be removed.
[quote, v1.5.5 | 14 August 2020]
Post-merger, PFB is now DB, PFB as a separate business entity will not be available after November 2020,
and this document has been updated to change all PFB to DB however both endpoints DE/PFB and DE/DB will work until end of November 2020.
From December 1st week DE/PFB will be decommissioned.
- Deprecated `PaymentInitiationService` and `PaymentInitiationValidationService` methods with `String` payment service/product parameters.
Methods with the corresponding enum parameters should be used instead.
- Renamed `xs2a-adapter-service-api-adapter` module into `xs2a-adapter-service-impl` and adjusted its
root package name to `de.adorsys.xs2a.adapter.impl`
- Removed `OauthToken` and replaced its usages with `TokenResponse`.
- Removed exchangeRate property in fiducia adapter according to the clarification from support.
- Changed the root package of the `xs2a-adapter-service-loader` module to `de.adapter.xs2a.adapter.serviceloader`.
- Changed the root package of the `xs2a-adapter-app` module to `de.adapter.xs2a.adapter.app`.
- Changed the root package of the `xs2a-adapter-rest-impl` module to `de.adapter.xs2a.adapter.rest.impl`.
- Changed the root package of the `deutsche-bank-adapter` module to `de.adapter.xs2a.adapter.deutschebank`.
- Changed the root package of the `dkb-adapter` module to `de.adapter.xs2a.adapter.dkb`.
- Changed the root package of the `sparda-bank-adapter` module to `de.adapter.xs2a.adapter.sparda`.
- Renamed `adorsys-integ-adapter` to `adorsys-adapter`.
- Changed the root package of the `unicredit-adapter` module to `de.adapter.xs2a.adapter.unicredit`.
- Changed the root package of the `xs2a-adapter-service-api` module to `de.adapter.xs2a.adapter.api`.
- Cleaned up package structure in `commerzbank-adapter`, `verlag-adapter` and `xs2a-adapter-service-remote`.
- Removed `maven-adapter-archetype`.
- Removed `PSU-ID` header from Payment Initiation and Consent Creation requests for `consors-bank-adapter`,
as the bank doesn't expect the header to be present within these requests.

== Features:
- Added transaction status mapping for periodic payments of ING
** EXPI -> CANC
** ACTV -> ACTC
- Added support for user-specified PKCE parameters to override default values.


== Fixes:
- Fixed class cast exception for periodic/pain.001 payment initiation for sparkasse
