= DRAFT Release notes for version 0.0.4 (release date: xx.xx.2019)

.Added banks
|===
|Bank Name|approach|AIS, PIS
|Santander Bank|n/a|AIS

|===

== Features:
- Adapters configuration moved to the link:../../xs2a-adapter-service-api/src/main/resources/adapter.config.properties[adapter.config.properties] file
- Added UI for manual managing aspsps (/manager endpoint). It is available only via `dev` profile
- Masking of sensitive data in the logs
- Logging of Correlation-ID header as a part of the Layout
- Added IMPORT endpoint to `aspsp-registry` for uploading and replacing Aspsp objects into Lucene repository. It is available only via `dev` profile
- Added endpoint for retrieving information about the application, such as name, version, description, etc (/actuator/info endpoint)

== Fixes:
- UpdatePsuAuthenticationResponse mapping exception fixed
- `xs2a-adapter-service-remote`. PaymentInitiationServiceImpl fixed problem with payment initiation status
- `xs2a-adapter-service-api`. AccountDetails - add missing @JsonValue annotations for AvailableAccountsEnum and AllPsd2Enum
