= DRAFT Release notes for version 0.0.10 (release date: xx.05.2020)

.Added banks
|===
|
|===

== Notices:
* PSD2 REST API and OAS file now are generated by `xs2a-adapter-codegen`.
As a consequence:
** `getTransactionDetails` operation added to psd2 ais;
** fixed inconsistent throws signatures;
** fixed missing `availableAccountsWithBalance` property on `AccountAccessTO`;
** fixed xs2a api model dependency of `TransactionDetailsTO.remittanceInformationStructured`;
** removed `TokenResponseTO` copy in psd2 package.
* Removed `AccountInformationService`, `PaymentInitiationService` methods deprecated in the previous release.
* Updated unicredit payment initiation service from v1.1 to v1.3.4

== Features:
* Added payment initiation service to ing-adapter

== Fixes:
* Fixed missing accessors for `AccountAccess.additionalInformation`.
* Fixed getPaymentInformation not able to handle xml responses.
* Fixed incorrect OAuth2 authorization url encoding when redirect_uri has its own parameters.
* Fixed incorrect mapping of payment transaction statuses from xs2a to psd2 api (e.g. RCVD -> Received).
* Fixed non-standard properties of ING not being propagated through psd2 api.
* Fixed NoClassDefFoundError due to exceptions thrown in static initialization blocks of dkb and santander services.
* Fixed "ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected" caused by responses with no body.
