= Draft Release notes for version 0.1.13 (release date: xx.07.2021)

.Added banks
|===
|===

== Notices:
- updated Postman collections.
- added support wiremock server as a standalone application.
- updated Adapter documentation, added details on bank's specific configurations and non-XS2A interfaces.
- changes in `adorsys-adapter`, removed AdorsysPaymentInitiationService, which contained a workaround for adding
a Creditor Address field. After the latest ModelBank environment updates, the address field is no more a mandatory data.
- updated WireMock stubs for `adorsys-adapter`, removed all periodic-payments and XML based payments as they are not
working at the moment.
- adjusted Xs2aHttpLogSanitizer to mask Account Ids in DKB error responses and Authorization Ids in the Commerzbank GET
Authorization URI requests.

== Features:
- Added "readAccountDetails" operation

== Fixes:
- fixed tests and test sequences in Postman collections
- fixed `adorsys-adapter` payment initiation failing if no Creditor Address was provided in JSON request.
- fixed `comdirect-adapter` issue with failing mapping LocalDateTime to OffsetDateTime.
