= DRAFT Release notes for version 0.1.2 (release date: xx.09.2020)

.Added banks
|===
|
|===

== Notices:
- Documentation was published on GitHub Pages and available by referencing to https://adorsys.github.io/xs2a-adapter/
- Moved `ScopeWithResourceIdOauth2Service` into the `adapter.adapter` package:
originally misplaced into the parent package.
- Renamed `xs2a-adapter-service-api-adapter` module into `xs2a-adapter-service-impl` and adjusted its
root package name to `de.adorsys.xs2a.adapter.impl`
- Removed `OauthToken` and replaced its usages with `TokenResponse`.
- Added transaction status mapping for periodic payments of ING
** EXPI -> CANC
** ACTV -> ACTC
- Removed exchangeRate property in fiducia adapter according to the clarification from support.
- Changed `xs2a-adapter-service-loader` module root package to `de.adapter.xs2a.adapter.serviceloader`.
- Changed `xs2a-adapter-app` module root package to `de.adapter.xs2a.adapter.app`.

== Features:


== Fixes:
- Fixed class cast exception for periodic/pain.001 payment initiation for sparkasse
