= DRAFT Release notes for version 0.1.2 (release date: xx.09.2020)

.Added banks
|===
|
|===

== Notices:
- Documentation was published on GitHub Pages and available by referencing to https://adorsys.github.io/xs2a-adapter/
- Renamed `xs2a-adapter-service-api-adapter` module into `xs2a-adapter-service-impl` and adjusted its
root package name to `de.adorsys.xs2a.adapter.impl`
- Removed `OauthToken` and replaced its usages with `TokenResponse`.
- Removed exchangeRate property in fiducia adapter according to the clarification from support.
- Changed the root package of the `xs2a-adapter-service-loader` module to `de.adapter.xs2a.adapter.serviceloader`.
- Changed the root package of the `xs2a-adapter-app` module to `de.adapter.xs2a.adapter.app`.
- Changed the root package of the `xs2a-adapter-rest-impl` module to `de.adapter.xs2a.adapter.rest.impl`.
- Changed the root package of the `deutsche-bank-adapter` module to `de.adapter.xs2a.adapter.deutschebank`.
- Changed the root package of the `dkb-adapter` module to `de.adapter.xs2a.adapter.dkb`.
- Changed the root package of the `sparda-bank-adapter` module to `de.adapter.xs2a.adapter.sparda`.

== Features:
- Added transaction status mapping for periodic payments of ING
** EXPI -> CANC
** ACTV -> ACTC
- Added support for user-specified PKCE parameters to override default values.


== Fixes:
- Fixed class cast exception for periodic/pain.001 payment initiation for sparkasse
