= Release notes for version 0.1.7 (release date: xx.02.2021)

.Added banks
|===
|===

== Notices:
- for `crealogix-adapter`: extended logging if getToken request fails, all logs are sanitized.
- for `crealogix-adapter`: Authorization header is resolved correctly now, it's decoded and split into Authorization
and PSD2-AUTHORIZATION headers.
- changes in `verlag-adapter`: Adapter will adjust getTransactionListAsString Accept header to contain _application/json_ value.
JSON is the only value the ASPSP is expecting in Accept header as for now.
Adapter will tolerate _text/plain_ as this is the only expected value in the ASPSP Sandbox environment.
A client will want to provide _text/plain_ intentionally to communicate with the Sandbox.
- for `crealogix-adapter`: PaymentInitiationService has the same behavior as AcountInformationService now - an Authorization
header, made by the Adapter, is decoded and replaced with new Authorization and PSD2-AUTHORIZATION headers with revealed values.

== Features:

== Fixes:
- fixed DKB `PSD2-AUTHORIZATION` header, it contains Base64 encoded value of `TPP-ID:TPP-SECRET` now
- fixed 406 error in `verlag-adapter` for `getTransactionList` call, if the `Accept` header has _accept all_ ("\*/*")
value or is absent, the **text/plain** value is provided.
- fixed bug in WiremockStubDifferenceDetectingInterceptor, isWiremockSupported method checks `mappings` directory
presence in an adapter as intended.
- fixed bug in `crealogix-adapter`: Authorization header credentials type recognized and checked correctly now.
- fixed authorization request uri construction in `commerzbank-adapter`
- fixed wrong bank response interpreting in `crealogix-adapter`. DKB custom `CrealogixValidationResponse` model was added,
and a mapper for proper mapping to TokenResponse was generated.
