= DRAFT Release notes for version 0.0.4 (release date: xx.xx.2019)

.Added banks
|===
|Bank Name|approach|AIS, PIS
|Santander Bank|n/a|AIS

|===

== Features:
- Adapters configuration moved to the link:../../xs2a-adapter-service-api/src/main/resources/adapter.config.properties[adapter.config.properties] file
- Added UI for manual managing aspsps (/manager endpoint). It is available only via `dev` profile
- Masking of sensitive data in the logs
- Logging of Correlation-ID header as a part of the Layout
- Added IMPORT endpoint to `aspsp-registry` for uploading and replacing Aspsp objects into Lucene repository. It is available only via `dev` profile
- Added endpoint for retrieving information about the application, such as name, version, description, etc (/actuator/info endpoint)
- Extended ASPSP schema with 2 new fields: IDP url and SCA approaches
- Added SCA approaches and IDP url columns on the registry UI
- Added swagger documentation for PSD2/Facade API, OAuth API and ASPSP Registry API
- Added PERSIST endpoint to `aspsp-registry` for replacing an original CSV of Aspsps with a new updated one. It is available only via `dev` profile
- Added Pagination feature on UI for `aspsp-registry`
- Added export and import endpoints to `aspsp-registry` module that accept JSON requests and produce JSON response.
- Moved to a single PKCS12 keystore for management of certificates, instead of relying on JVM wide default `javax.net.ssl.keyStore`
- Updated Fiducia `GET transactions` flow to make it respond with `400` on unsupported booking status in request

== Fixes:
- UpdatePsuAuthenticationResponse mapping exception fixed
- `xs2a-adapter-service-remote`. PaymentInitiationServiceImpl fixed problem with payment initiation status
- `xs2a-adapter-service-api`. AccountDetails - add missing @JsonValue annotations for AvailableAccountsEnum and AllPsd2Enum
- `xs2a-adapter-rest-impl`. index, main - fixed mdl-tooltip bug
- `xs2a-adapter-service-api`. BasePaymentInitiationService - fix initiateSinglePayment URL, change path constants visibility so they can be reused in extensions
