= Release notes for version 0.0.2 (release date: 05.08.2019)

.Implemented AIS requests
|===
|BG Spec summary|BG Spec operationId
|Delete consent|*_deleteConsent_*
|===


.Added banks
|===
|Bank Name|approach

|Commerzbank|redirect (OAuth)
|===

== Changes:

* The project was renamed from xs2a-gateway to xs2a-adapter to avoid misunderstanding with another adorsys project
* Adapter configuration was decoupled from the code and now is sourced from a csv file.
* Added a possibility to provide a custom CSV file for adapter configuration through application environment variable `csv.aspsp.adapter.config.file.path`
* Added adapter resolution by `ASPSP-ID` in the _aspsp-regisry_
* Added AspspSearchService (/v1/aspsps endpoint) for lookup of `ASPSP-ID` in the aspsp-registry by different fields.
A fuzzy search by name and prefix search by bic and bank code are currently supported.
* Added feign client for xs2a-adapter. link:../../xs2a-adapter-service-remote/README.md[Read more here]
* Added `DELETE consent` endpoint and implemented the entire flow for current operation
