= Release notes for version 0.1.0 (release date: 10.07.2020)

== Notices:
- PSD2 API has been removed.
- Number of copies of schema classes was reduced from 4 to 1.
The remaining set is generated from the yaml file into xs2a-adapter-generated-api module (`api.model` package).
This fixes the issue of model copies getting out-of-sync and prevents its occurrence in the future.
- Generated rest api has been moved to `rest.api` package.
- Added equals and hashCode methods to generated models.
- `fromValue` static factory methods of generated enums returns null for unrecognizied values instead of throwing an exception.
- Removed `xs2a-adapter-service-remote-spring` module: regular remote is spring dependent.
- Added support for `periodic-payments/pain.001-sepa-credit-transfers` (multipart).

== Features:
- Implemented periodic payments support.
- Added `Oauth2Service` for santander.
- Introduced `audit.sanitized` property to have the possibility to mask request URLs in `operation` MDC property. The default value is `true`.

== Fixes:
- Fixed wrong OAuth param validation for Comdirect, Commerzbank and Sparkasse
- Fixed requests without a payload not being logged.
- Sanitized payments request URLs
- Unicredit. Added `PSU-ID-TYPE` header for PIS requests
