@startuml
participant tpp as "TPP"
participant adapter as "XS2A\nAdapter"
participant bank as "ASPSP"

tpp->adapter: account information consent request
|||
adapter->bank: account information consent request
|||
adapter<-bank: 201 account-information response (startAuthorisation link)
|||
tpp<-adapter: 201 account-information response (startAuthorisation link)
|||
group psu authorisation
tpp->adapter: start authorisation request (psu credentials)
|||
adapter->bank: start authorisation request (psu credentials)
|||
adapter<-bank: 201 start-authorisation response (available sca methods)
|||
tpp<-adapter: 201 start-authorisation response (available sca methods)
|||
tpp->adapter: authorisation update request (sca method)
|||
adapter->bank: authorisation update request (sca method)
|||
adapter<-bank: 200 authorisation-update response
|||
tpp<-adapter: 200 authorisation-update response
|||
tpp->adapter: authorisation update request (otp)
|||
adapter->bank: authorisation update request (otp)
|||
adapter<-bank: 200 authorisation-update response
|||
tpp<-adapter: 200 authorisation-update response
end
|||
tpp->adapter: get account list request
|||
adapter->bank: get account list request
|||
adapter<-bank: 200 account-list response
|||
tpp<-adapter: 200 account-list response
|||
tpp->adapter: get transaction list request
|||
adapter->bank: get transaction list request
|||
adapter<-bank: 200 transaction-list response
|||
tpp<-adapter: 200 transaction-list response
|||
opt get consent status
tpp->adapter: get consent status
|||
adapter->bank: get consent status
|||
adapter<-bank: 200 consent status response
|||
tpp<-adapter: 200 consent status response
end
|||
opt get sca status
tpp->adapter: get sca status request
|||
adapter->bank: get sca status request
|||
adapter<-bank: 200 sca-status response
|||
tpp<-adapter: 200 sca-status response
end
@enduml
