@startuml
participant tpp as "TPP"
participant adapter as "XS2A\nAdapter"
participant bank as "ASPSP"

tpp->adapter: payment initiation request
|||
adapter->bank: payment initiation request
|||
adapter<-bank: 201 payment initiation response \n(message: authorise the transaction via app „xxx“)
|||
tpp<-adapter: 201 payment initiation response \n(message: authorise the transaction via app „xxx“)
|||
ref over tpp, adapter, bank: The ASPSP pushes the challenge to an authorisation app or device.\nPSU authorises the payment
|||
tpp->adapter: payment status request
|||
adapter->bank: payment status request
|||
adapter<-bank: 200 payment-status response
|||
tpp<-adapter: 200 payment-status response
|||
opt get sca status
tpp->adapter: get sca status request
|||
adapter->bank: get sca status request
|||
adapter<-bank: 200 sca-status response
|||
tpp<-adapter: 200 sca-status response
end
@enduml