@startuml
participant tpp as "TPP"
participant adapter as "XS2A\nAdapter"
participant bank as "ASPSP"

tpp->adapter: payment initiation request
|||
group #LightBlue get application token [ing specific]
adapter->bank: get application token request
|||
adapter<-bank: 200 application-token response
end
|||
adapter->bank: payment initiation request
|||
adapter<-bank: 201 payment initiation response (scaRedirect link)
|||
tpp<-adapter: 201 payment initiation response (scaRedirect link)
|||
ref over tpp, adapter, bank: PSU interaction with an authorisation webpage of the ASPSP
|||
tpp<-bank: redirect back
|||
tpp->adapter: payment status request
|||
adapter->bank: payment status request
|||
adapter<-bank: 200 payment-status response
|||
tpp<-adapter: 200 payment-status response
@enduml
