@startuml
participant tpp as "TPP"
participant adapter as "XS2A\nAdapter"
participant bank as "ASPSP"

tpp->adapter: payment initiation request
|||
adapter->bank: payment initiation request
|||
adapter<-bank: 201 payment-initiation response (scaOauth link)
|||
tpp<-adapter: 201 payment-initiation response (scaOauth link)
|||
group oauth2 sca
tpp->adapter: get authorization url request
|||
opt get authorization server metadata
adapter->bank: get authorization endpoint request
|||
adapter<-bank: 200 authorization-endpoint response
end
tpp<-adapter: 200 redirect url
|||
ref over tpp, adapter, bank: PSU interaction with an authorisation service of the ASPSP
|||
tpp<-bank: redirect back (authorization code)
|||
tpp->adapter: get access token (exchange code)
|||
opt get authorization server metadata
adapter->bank: get token endpoint request
|||
adapter<-bank: 200 token-endpoint response
end
|||
adapter->bank: get access token (exchange code)
|||
adapter<-bank: 200 token response
|||
tpp<-adapter: 200 token response
end
|||
tpp->adapter: payment status request
|||
adapter->bank: payment status request
|||
adapter<-bank: 200 payment-status response
|||
tpp<-adapter: 200 payment-status response
|||
opt get sca status
tpp->adapter: get sca status request
|||
adapter->bank: get sca status request
|||
adapter<-bank: 200 sca-status response
|||
tpp<-adapter: 200 sca-status response
end
@enduml
