@startmindmap
+ BaseAccountInformationService
++ AdorsysAccountInformationService
++ ComdirectAccountInformationService
++ CommerzbankAccountInformationService
++ ConsorsAccountInformationService
++ CrealogixAccountInformationService
++ DeutscheBankAccountInformationService
++ FiduciaAccountInformationService
++ IngAccountInformationApi
++ XAccountInformationService
@endmindmap
