@startmindmap
* RuntimeException
** AccessTokenException
** AdapterNotFoundException
** AspspRegistrationException
*** AspspRegistrationNotFoundException
** BadRequestException
** ErrorResponseException
** HttpRequestSigningException
** IbanException
** NotAcceptableException
** OAuthException
** PsuPasswordEncodingException
** RequestValidationException
*** RequestAuthorizationValidationException
** UncheckedSSLHandshakeException
** Xs2aAdapterException
@endmindmap