@startuml
skinparam rectangle {
    BackgroundColor black
    FontColor white
}

title BlackBox

interface "aspsp search" as aspsp
rectangle "xs2a adapter" as adapter

adapter #-right-() oAuth: interface
adapter #-down-() aspsp: interface
adapter #-left-() xs2a: interface

@enduml
