@startuml
actor TPP as tpp
collections ASPSPs as banks

package xs2a_adapter [
+ xs2a-adapter-app
+ xs2a-adapter-service-api
+ xs2a-adapter-service-loader
+ xs2a-adapter-service-remote
+ xs2a-adapter-service-api-adapter
+ xs2a-adapter-rest-api
+ xs2a-adapter-generated-rest-api
+ xs2a-adapter-rest2api-mapper
+ xs2a-adapter-rest-impl
+ xs2a-adapter-aspsp-registry
+ adapters
]

tpp -> xs2a_adapter: AIS and PIS requests
xs2a_adapter -> banks: transform request\n to the bank specific language

@enduml
