server:
  port: 8081

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    artifactId: @project.artifactId@

spring:
  application:
    name: xs2a-gateway

logging.level.org.apache.http.wire: DEBUG
