@startuml

title Whitebox Level 2

component "service-loader\n" as r {
        rectangle "AIS" as ais
        rectangle "PIS" as pis
 }

 interface "Bank adapters" as ba

 ais -right-() " "
 pis -left-() "  "
 ais -(0- ba
 pis -(0- ba

@enduml
