apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xs2a-adapter.fullname" . }}-config
  labels:
    {{- include "xs2a-adapter.labels" . | nindent 4 }}
data:
  {{- if and .Values.logback.enabled }}
  logback.xml: |
    {{- (.Files.Get (.Values.logback.file)) | nindent 4 }}
  {{- end }}
  {{- if .Values.adapter.aspspConfig }}
  aspsp-adapter-config.csv: |
    {{- (.Files.Get (.Values.adapter.aspspConfigFile)) | nindent 4 }}
  {{- end }}
  adapter.config.properties: |
    {{- (.Files.Get (.Values.adapter.adapterConfigFile)) | nindent 4 }}
  {{- if .Values.adapter.logSanitizerWhitelist.enabled }}
  log-sanitizer-whitelist: |
    {{- (.Files.Get (.Values.adapter.logSanitizerWhitelist.file)) | nindent 4 }}
  {{- end }}
