{{ if .Values.adapter.route.enabled }}
{{ if eq .Values.cluster.type "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "xs2a-adapter.labels" . | nindent 4 }}
  name: {{ include "xs2a-adapter.fullname" . }}
spec:
  host: {{ .Values.adapter.route }}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xs2a-adapter
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
