apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "xs2a-adapter.labels" . | nindent 4 }}
  name: {{ include "xs2a-adapter.fullname" . }}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8081
  selector:
    {{- include "xs2a-adapter.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
