---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xs2a-adapter-config
  labels:
    app: xs2a-adapter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
