apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: xs2a-adapter
  name: xs2a-adapter
spec:
  host: {{ .Values.adapter.route }}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xs2a-adapter
    weight: 100
  wildcardPolicy: None
