name: Docker CI
on:
  push:
    branches:
      - master

env:
  XS2A_ADAPTER_IMAGE_NAME: xs2a-adapter
  XS2A_ADAPTER_IMAGE_TAG: latest
  XS2A_ADAPTER_ORGANIZATION_NAME: adorsys

jobs:
  build-and-push-to-dockerhub:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: mvn clean package -Dmaven.test.skip=true -B

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        env:
          DOCKERHUB_IMAGE_NAME: ${{ env.XS2A_ADAPTER_ORGANIZATION_NAME }}/${{ env.XS2A_ADAPTER_IMAGE_NAME }}:${{ env.XS2A_ADAPTER_IMAGE_TAG }}
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_NAME }}
