name: Release CI
on:
  push:
    tags:
      - v*

jobs:
  build-and-push-to-dockerhub:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: mvn clean package -Dmaven.test.skip=true -B -ntp

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get project version
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v5
        env:
          DOCKERHUB_IMAGE_NAME: ${{ github.repository }}:${{ env.DOCKER_TAG }}
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_NAME }}

  build:
    name: Publish project artifacts to Maven Central
    needs: build-and-push-to-dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to publish to GitHub Packages

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Central and GitHub
        run: mvn clean deploy -P release -s ./scripts/mvn-release-settings.xml -ntp -DskipTests -U
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

#  build-and-deploy-docs:
#    name: Build and deploy documentation
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Git checkout
#        uses: actions/checkout@v4
#
#      - run: chmod +x docs-generator.sh
#
#      - name: Generate Website
#        run: ./docs-generator.sh
#
#      - name: Deploy to Github Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./tmp
